# Generated by Django 4.2.5 on 2023-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_libraries", "0001_add_book_and_borrow_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="nearest_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowhistory",
            name="deadline_date",
            field=models.DateField(),
        ),
    ]
