# Generated by Django 4.2.5 on 2023-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_libraries", "0002_adjust_attr_book_and_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowhistory",
            name="deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
